ALTER TABLE stations
    ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;


ALTER TABLE trains
    ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;


ALTER TABLE coaches
    ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;


ALTER TABLE seats
    ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;