ALTER TABLE bookings

    ADD COLUMN IF NOT EXISTS start_order INTEGER NOT NULL DEFAULT 0;


ALTER TABLE bookings

    ADD COLUMN IF NOT EXISTS end_order INTEGER NOT NULL DEFAULT 0;


ALTER TABLE bookings

    ADD COLUMN IF NOT EXISTS status VARCHAR (50);


ALTER TABLE bookings

    ADD COLUMN IF NOT EXISTS fare NUMERIC (10,2);
